### ISSUE TITLE
add domains for all English words that are 5L or less for the  top 200 most popular extensions

### ISSUE THREAD

**Issue by timbowhite** [timbowhite/wee.domains-tracker#11]
There are ~22K English words with 5 or fewer characters.

22,000 * 200 = 4.4M new domains to be added and checked.

**Comment by pixelyo** [comment]
generally would I be interested in all 5L **.com** domains, since 100% of <=4L or <=5N .com domains are taken

**Comment by timbowhite** [comment]
> generally would I be interested in all 5L **.com** domains, since 100% of <=4L or <=5N .com domains are taken

That's a good idea, .com is king.

5L .com: 26^5 = 11,881,376 domains to be added and checked.

I've started this on wee.domains, you can see the progress on the statistics page:

[https://wee.domains/statistics#com](https://wee.domains/statistics#com)

It just started so the progress is currently 0.15%.

And I've made a custom list for the results:

[https://wee.domains/v/eyxapqmd](https://wee.domains/v/eyxapqmd)

The entire process for all 11.8M domains may take a week or two to complete.

**Comment by timbowhite** [comment]
The top 25k most popular English words (regardless of character count) have been added for the following suffixes: com,net,org,io,ai,top,co,xyz,io,me,info.

https://wee.domains/domains/english-words

Domains are being added for the remaining 189 most popular domain extensions. This process will take about 2 weeks.
