### ISSUE TITLE
Add automatic and working TLS cert renewal

### ISSUE THREAD

**Issue by wasdennnoch** [timbowhite/wee.domains-tracker#32]
:)

![](https://im-a-dolphin.de/s/01ebdb2.png)

**Comment by timbowhite** [comment]
Thank you! Cert has been renewed.

**Comment by kylefmohr** [comment]
@timbowhite expired again

**Comment by timbowhite** [comment]
Thanks, this has been fixed.

**Comment by timbowhite** [comment]
Automated TLS renewals have been implemented for wee.domains.
