### ISSUE TITLE
.wang domains not being marked as premium 

### ISSUE THREAD

**Issue by kylefmohr** [timbowhite/wee.domains-tracker#33]
Appears to affect tld-list as well. As far as I can tell, all 1-2 character .wang domains are considered premium, and cost multiple thousands of dollars to register.

**Comment by timbowhite** [comment]
Verified.

On wee.domains, it appears there a number of cases of this incorrect pricing model (i.e. o.wang, re.wang, is.wang have registration @ $3.90).

tld-list.com is returning all .wang's as regular pricing model.

L and LL registrations should be premium around $33k and $3k, respectively.

I'll look into it.

**Comment by timbowhite** [comment]
This should now be corrected on wee.domains.

For tld-list, I've submitted a bug report to the provider of this data, I expect they'll have this fixed this week.

**Comment by timbowhite** [comment]
This has now been fixed on tld-list.com.
